<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // ── KATEGORI 1: Keramik & Gerabah (category_id = 1, total 11 kriya) ──
            [
                'shop_id' => 1,
                'category_id' => 1,
                'name' => 'Vas Bunga Keramik Ulir Terracotta',
                'description' => 'Vas bunga keramik bertekstur ulir terracotta, dibakar dengan oven tradisional suhu tinggi untuk dekorasi ruang tamu yang hangat dan alami.',
                'price' => 185000,
                'stock' => 15,
                'weight' => 1500,
                'images' => ['https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=600&auto=format&fit=crop'],
                'tags' => ['Vas Bunga', 'Terracotta', 'Gerabah'],
                'style' => 'Vintage',
                'target_demographic' => 'dewasa',
                'rating_avg' => 4.9,
            ],
            [
                'shop_id' => 6,
                'category_id' => 1,
                'name' => 'Set Cangkir Keramik Kasongan Terakota',
                'description' => 'Set isi 4 cangkir keramik tanah liat Kasongan Yogyakarta tanpa gagang dengan sentuhan gradasi warna alami, dibakar dengan tungku kayu tradisional.',
                'price' => 110000,
                'stock' => 20,
                'weight' => 600,
                'images' => ['https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=600&auto=format&fit=crop'],
                'tags' => ['Cangkir Keramik', 'Terakota', 'Kasongan'],
                'style' => 'Etnik',
                'target_demographic' => 'dewasa',
                'rating_avg' => 4.8,
            ],
            [
                'shop_id' => 6,
                'category_id' => 1,
                'name' => 'Teko Keramik Terakota Melati Bali',
                'description' => 'Teko keramik tanah liat merah alami bermotif bunga melati Bali timbul buatan tangan. Dilengkapi saringan teh terintegrasi di dalamnya.',
                'price' => 310000,
                'stock' => 10,
                'weight' => 900,
                'images' => ['https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=600&auto=format&fit=crop'],
                'tags' => ['Teko Keramik', 'Terakota', 'Teh Bali'],
                'style' => 'Etnik',
                'target_demographic' => 'dewasa',
                'rating_avg' => 4.8,
            ],
            [
                'shop_id' => 6,
                'category_id' => 1,
                'name' => 'Set Piring & Mangkuk Keramik Kasongan',
                'description' => 'Set perangkat makan lengkap handmade Kasongan terdiri dari piring saji, mangkuk sup, cangkir, dan tatakan dengan glasir abu-abu doff bertekstur wabi-sabi.',
                'price' => 240000,
                'stock' => 12,
                'weight' => 2500,
                'images' => ['/images/products/dinnerware.png'],
                'tags' => ['Set Piring', 'Mangkuk', 'Kasongan'],
                'style' => 'Minimalis',
                'target_demographic' => 'dewasa',
                'rating_avg' => 4.9,
            ],
            [
                'shop_id' => 6,
                'category_id' => 1,
                'name' => 'Mug Keramik Lukis Solo Hand-painted',
                'description' => 'Mug kopi keramik berkualitas dengan lukisan tangan motif batik canting khas Solo yang elegan dan unik pada setiap cangkirnya.',
                'price' => 38000,
                'stock' => 30,
                'weight' => 350,
                'images' => ['https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&auto=format&fit=crop'],
                'tags' => ['Mug Batik', 'Keramik Solo', 'Hand-painted'],
                'style' => 'Etnik',
                'target_demographic' => 'remaja',
                'rating_avg' => 4.7,
            ],
            [
                'shop_id' => 6,
                'category_id' => 1,
                'name' => 'Mug Kopi Stoneware Abu-Abu Doff',
                'description' => 'Mug kopi stoneware berkapasitas 350ml warna abu-abu doff bertekstur kasar khas pegunungan, nyaman digenggam saat kuliah pagi.',
                'price' => 78000,
                'stock' => 25,
                'weight' => 400,
                'images' => ['https://images.unsplash.com/photo-1577937927133-66ef06acdf18?w=600&auto=format&fit=crop'],
                'tags' => ['Mug Kopi', 'Stoneware', 'Abu-abu'],
                'style' => 'Minimalis',
                'target_demographic' => 'mahasiswa',
                'rating_avg' => 4.8,
            ],
            [
                'shop_id' => 6,
                'category_id' => 1,
                'name' => 'Mangkuk Ramen Keramik Tekstur Alami',
                'description' => 'Mangkuk ramen keramik tebal dengan guratan kuas manual perajin tembikar, menahan panas kuah ramen lebih lama bergaya aesthetic.',
                'price' => 95000,
                'stock' => 18,
                'weight' => 650,
                'images' => ['https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&auto=format&fit=crop'],
                'tags' => ['Mangkuk Ramen', 'Mangkuk Keramik', 'Tembikar'],
                'style' => 'Aesthetic',
                'target_demographic' => 'mahasiswa',
                'rating_avg' => 4.8,
            ],
            [
                'shop_id' => 1,
                'category_id' => 1,
                'name' => 'Gerabah Pot Gantung Terakota',
                'description' => 'Pot tanaman gantung dari gerabah tanah liat terakota alami berpori untuk pernapasan akar tanaman hias yang sehat.',
                'price' => 45000,
                'stock' => 35,
                'weight' => 1200,
                'images' => ['https://images.unsplash.com/photo-1545241047-6083a3684587?w=600&auto=format&fit=crop'],
                'tags' => ['Pot Gantung', 'Terakota', 'Gerabah'],
                'style' => 'Vintage',
                'target_demographic' => 'dewasa',
                'rating_avg' => 4.6,
            ],
            [
                'shop_id' => 1,
                'category_id' => 1,
                'name' => 'Tempat Lilin Aromaterapi Tanah Liat',
                'description' => 'Tempat lilin aroma terapi berlubang-lubang artistik buatan tangan Kasongan, memancarkan cahaya lilin temaram yang menenangkan jiwa.',
                'price' => 32000,
                'stock' => 40,
                'weight' => 300,
                'images' => ['/images/products/tempat_lilin_tanah_liat.jpg'],
                'tags' => ['Tempat Lilin', 'Tanah Liat', 'Aromaterapi'],
                'style' => 'Bohemian',
                'target_demographic' => 'remaja',
                'rating_avg' => 4.7,
            ],
            [
                'shop_id' => 6,
                'category_id' => 1,
                'name' => 'Dispenser Sabun Cair Keramik Handmade',
                'description' => 'Dispenser tempat sabun cair kamar mandi dari keramik buatan tangan bertekstur, mempercantik estetika wastafel rumah modern.',
                'price' => 85000,
                'stock' => 15,
                'weight' => 500,
                'images' => ['/images/products/dispenser_sabun_cair.jpg'],
                'tags' => ['Dispenser Sabun', 'Keramik Wastafel', 'Kamar Mandi'],
                'style' => 'Minimalis',
                'target_demographic' => 'mahasiswa',
                'rating_avg' => 4.7,
            ],
            [
                'shop_id' => 1,
                'category_id' => 1,
                'name' => 'Piring Saji Keramik Oval Motif Batik',
                'description' => 'Piring saji berbentuk oval berbahan stoneware dengan lukisan batik mega mendung manual di bagian tengah yang anggun.',
                'price' => 155000,
                'stock' => 8,
                'weight' => 850,
                'images' => ['/images/products/piring_saji_batik.jpg'],
                'tags' => ['Piring Saji', 'Keramik Batik', 'Mega Mendung'],
                'style' => 'Etnik',
                'target_demographic' => 'dewasa',
                'rating_avg' => 4.9,
            ],
            [
                'shop_id' => 6,
                'category_id' => 1,
                'name' => 'Lilin Aromaterapi Gelas Keramik Bali',
                'description' => 'Lilin aromaterapi premium dari kedelai alami wangi lavender, dituangkan langsung ke dalam gelas keramik handmade khas perajin tembikar Bali.',
                'price' => 65000,
                'stock' => 25,
                'weight' => 300,
                'images' => ['/images/products/lilin_aromaterapi_gelas.png'],
                'tags' => ['Lilin Aromaterapi', 'Keramik Bali', 'Lavender'],
                'style' => 'Bohemian',
                'target_demographic' => 'remaja',
                'rating_avg' => 4.8,
            ],

            // ── KATEGORI 2: Kayu & Pahat (category_id = 2, total 11 kriya) ──
            [
                'shop_id' => 4,
                'category_id' => 2,
                'name' => 'Mainan Balok Kayu Montessori',
                'description' => 'Mainan edukasi balok susun dari kayu pinus halus tanpa pewarna kimia beracun, aman untuk stimulasi tumbuh kembang anak.',
                'price' => 135000,
                'stock' => 25,
                'weight' => 800,
                'images' => ['/images/products/mainan_balok_montessori.jpg'],
                'tags' => ['Montessori', 'Edukasi', 'Mainan Anak'],
                'style' => 'Minimalis',
                'target_demographic' => 'anak-anak',
                'rating_avg' => 4.9,
            ],
            [
                'shop_id' => 4,
                'category_id' => 2,
                'name' => 'Puzzle Geometri Kayu Edukatif',
                'description' => 'Puzzle bentuk geometri warna-warni dari pewarna makanan alami kayu mahoni halus, merangsang motorik halus balita.',
                'price' => 68000,
                'stock' => 30,
                'weight' => 400,
                'images' => ['/images/products/puzzle_geometri.jpg'],
                'tags' => ['Puzzle', 'Kayu', 'Motorik'],
                'style' => 'Minimalis',
                'target_demographic' => 'anak-anak',
                'rating_avg' => 4.7,
            ],
            [
                'shop_id' => 4,
                'category_id' => 2,
                'name' => 'Mainan Mobil-mobilan Kayu Tradisional',
                'description' => 'Mainan mobil kayu jati sisa produksi industri mebel Jepara pilihan yang dirakit manual sangat halus tanpa paku besi.',
                'price' => 48000,
                'stock' => 40,
                'weight' => 300,
                'images' => ['https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=600&auto=format&fit=crop'],
                'tags' => ['Mainan Kayu', 'Tradisional', 'Mobil'],
                'style' => 'Vintage',
                'target_demographic' => 'anak-anak',
                'rating_avg' => 4.6,
            ],
            [
                'shop_id' => 4,
                'category_id' => 2,
                'name' => 'Tempat Pensil Kayu Jati Minimalis',
                'description' => 'Tempat pensil minimalis dari kayu jati solid bertekstur serat alami lurus dengan 3 kompartemen pembagi meja belajar.',
                'price' => 45000,
                'stock' => 35,
                'weight' => 500,
                'images' => ['https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=600&auto=format&fit=crop'],
                'tags' => ['Tempat Pensil', 'Kayu Jati', 'Meja Belajar'],
                'style' => 'Minimalis',
                'target_demographic' => 'mahasiswa',
                'rating_avg' => 4.6,
            ],
            [
                'shop_id' => 4,
                'category_id' => 2,
                'name' => 'Kotak Perhiasan Kayu Ukir Jati',
                'description' => 'Kotak perhiasan berukir relief motif bunga melati Jepara dari kayu jati solid, bagian dalam dilapisi kain beludru merah maroon halus.',
                'price' => 195000,
                'stock' => 18,
                'weight' => 900,
                'images' => ['/images/products/kotak_perhiasan.jpg'],
                'tags' => ['Kotak Perhiasan', 'Kayu Jati', 'Ukir'],
                'style' => 'Etnik',
                'target_demographic' => 'dewasa',
                'rating_avg' => 4.9,
            ],
            [
                'shop_id' => 4,
                'category_id' => 2,
                'name' => 'Nampan Kayu Jati Solid Hexagonal',
                'description' => 'Nampan saji berbentuk segi enam (hexagonal) dengan serat kayu jati alami yang sangat tebal berkesan aesthetic bohemian.',
                'price' => 85000,
                'stock' => 30,
                'weight' => 500,
                'images' => ['/images/products/nampan_hexagonal.jpg'],
                'tags' => ['Nampan Kayu', 'Jati', 'Hexagonal'],
                'style' => 'Minimalis',
                'target_demographic' => 'dewasa',
                'rating_avg' => 4.7,
            ],
            [
                'shop_id' => 4,
                'category_id' => 2,
                'name' => 'Hiasan Dinding Kayu Pahat Kaligrafi',
                'description' => 'Pajangan hiasan dinding dari kayu jati berkualitas berukir kaligrafi arab yang dipahat tangan langsung oleh master kriya Jepara.',
                'price' => 280000,
                'stock' => 5,
                'weight' => 1600,
                'images' => ['https://images.unsplash.com/photo-1618220179428-22790b461013?w=600&auto=format&fit=crop'],
                'tags' => ['Hiasan Dinding', 'Pahat', 'Kaligrafi'],
                'style' => 'Etnik',
                'target_demographic' => 'dewasa',
                'rating_avg' => 4.8,
            ],
            [
                'shop_id' => 4,
                'category_id' => 2,
                'name' => 'Sendok & Garpu Kayu Mahoni Set',
                'description' => 'Satu set sendok, garpu, dan sumpit dari kayu mahoni berfinishing alami minyak kelapa food-grade, cocok untuk alat makan ramah lingkungan mahasiwa kos.',
                'price' => 35000,
                'stock' => 80,
                'weight' => 120,
                'images' => ['https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop'],
                'tags' => ['Alat Makan', 'Kayu Mahoni', 'Zero Waste'],
                'style' => 'Minimalis',
                'target_demographic' => 'mahasiswa',
                'rating_avg' => 4.7,
            ],
            [
                'shop_id' => 4,
                'category_id' => 2,
                'name' => 'Tatakan Gelas Kayu Pinus Alami (Set isi 6)',
                'description' => 'Enam tatakan gelas dari potongan melintang kayu pinus alami bertekstur melingkar konsentris, mempercantik estetika meja kerja.',
                'price' => 52000,
                'stock' => 45,
                'weight' => 350,
                'images' => ['/images/products/tatakan_gelas.jpg'],
                'tags' => ['Tatakan Gelas', 'Kayu Pinus', 'Aesthetic'],
                'style' => 'Aesthetic',
                'target_demographic' => 'remaja',
                'rating_avg' => 4.8,
            ],
            [
                'shop_id' => 4,
                'category_id' => 2,
                'name' => 'Mangkuk Salad Kayu Sungkai Besar',
                'description' => 'Mangkuk kayu besar bertekstur guratan kayu sungkai putih alami, sangat cantik untuk menyajikan salad atau buah segar keluarga.',
                'price' => 145000,
                'stock' => 12,
                'weight' => 600,
                'images' => ['/images/products/mangkuk_salad.jpg'],
                'tags' => ['Mangkuk Salad', 'Kayu Sungkai', 'Dapur'],
                'style' => 'Minimalis',
                'target_demographic' => 'dewasa',
                'rating_avg' => 4.8,
            ],
            [
                'shop_id' => 4,
                'category_id' => 2,
                'name' => 'Rak Dinding Gantungan Kunci Rustic',
                'description' => 'Rak gantung dinding mini dengan 4 gantungan kunci kuningan dari kayu palet daur ulang bertekstur rustic vintage.',
                'price' => 59000,
                'stock' => 20,
                'weight' => 450,
                'images' => ['https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?w=600&auto=format&fit=crop'],
                'tags' => ['Rak Kunci', 'Kayu Rustic', 'Pajangan'],
                'style' => 'Vintage',
                'target_demographic' => 'remaja',
                'rating_avg' => 4.7,
            ],
            [
                'shop_id' => 4,
                'category_id' => 2,
                'name' => 'Dudukan HP & Organizer Kayu Jati',
                'description' => 'Dudukan smartphone minimalis sekaligus organizer meja belajar dari kayu jati solid, sangat stabil dan elegan untuk WFH atau belajar.',
                'price' => 48000,
                'stock' => 25,
                'weight' => 300,
                'images' => ['/images/products/dudukan_hp_organizer.jpg'],
                'tags' => ['Dudukan HP', 'Organizer Meja', 'Kayu Jati'],
                'style' => 'Minimalis',
                'target_demographic' => 'mahasiswa',
                'rating_avg' => 4.8,
            ],

            // ── KATEGORI 3: Tekstil & Batik (category_id = 3, total 11 kriya) ──
            [
                'shop_id' => 2,
                'category_id' => 3,
                'name' => 'Kain Batik Tulis Jogja Motif Parang',
                'description' => 'Kain batik tulis tradisional katun primisima kualitas terbaik, digambar canting lilin malam panas pewarna soga alam khas Yogyakarta.',
                'price' => 450000,
                'stock' => 6,
                'weight' => 350,
                'images' => ['/images/products/batik_parang.jpg'],
                'tags' => ['Batik Tulis', 'Batik Jogja', 'Kain Batik'],
                'style' => 'Etnik',
                'target_demographic' => 'dewasa',
                'rating_avg' => 5.0,
            ],
            [
                'shop_id' => 5,
                'category_id' => 3,
                'name' => 'Syal Tenun Ikat Lombok Tradisional',
                'description' => 'Syal tenun ikat Sade Lombok ditenun benang warna tumbuhan alami menggunakan Alat Tenun Bukan Mesin (ATBM).',
                'price' => 165000,
                'stock' => 14,
                'weight' => 200,
                'images' => ['/images/products/tenun_lombok.jpg'],
                'tags' => ['Tenun Ikat', 'Syal Lombok', 'Handwoven'],
                'style' => 'Etnik',
                'target_demographic' => 'dewasa',
                'rating_avg' => 4.8,
            ],
            [
                'shop_id' => 2,
                'category_id' => 3,
                'name' => 'Batik Cap Kemeja Pria Modern',
                'description' => 'Kemeja batik pria slimfit motif cap tembaga berkualitas tinggi dari perajin Laweyan Solo, katun adem semi-formal.',
                'price' => 225000,
                'stock' => 20,
                'weight' => 250,
                'images' => ['/images/products/kemeja_batik.png'],
                'tags' => ['Kemeja Batik', 'Batik Cap', 'Batik Pria'],
                'style' => 'Modern',
                'target_demographic' => 'dewasa',
                'rating_avg' => 4.7,
            ],
            [
                'shop_id' => 3,
                'category_id' => 3,
                'name' => 'Gelang Manik Kelopak Bunga Daisy',
                'description' => 'Gelang manik-manik tali elastis dengan motif rangkaian bunga Daisy retro pastel imut yang sedang populer di kalangan remaja.',
                'price' => 15000,
                'stock' => 100,
                'weight' => 50,
                'images' => ['/images/products/gelang_daisy.png'],
                'tags' => ['Gelang', 'Manik-manik', 'Aksesori'],
                'style' => 'Cute',
                'target_demographic' => 'remaja',
                'rating_avg' => 4.8,
            ],
            [
                'shop_id' => 3,
                'category_id' => 3,
                'name' => 'Set Pin Enamel Estetik Retro',
                'description' => 'Set isi 3 bros pin enamel logam bertema pop art retro aesthetic untuk dekorasi tas kanvas kuliah atau jaket denim.',
                'price' => 35000,
                'stock' => 50,
                'weight' => 80,
                'images' => ['/images/products/pin_enamel.jpg'],
                'tags' => ['Pin Enamel', 'Retro', 'Aesthetic'],
                'style' => 'Aesthetic',
                'target_demographic' => 'remaja',
                'rating_avg' => 4.9,
            ],
            [
                'shop_id' => 3,
                'category_id' => 3,
                'name' => 'Ikat Rambut Scrunchie Sutra Pastel',
                'description' => 'Scrunchie sutra mulberry isi 3 pcs dengan warna pastel aesthetic, sangat lembut mencegah kerontokan rambut remaja.',
                'price' => 29000,
                'stock' => 60,
                'weight' => 50,
                'images' => ['/images/products/scrunchie_pastel.jpg'],
                'tags' => ['Scrunchie', 'Ikat Rambut', 'Sutra'],
                'style' => 'Cute',
                'target_demographic' => 'remaja',
                'rating_avg' => 4.7,
            ],
            [
                'shop_id' => 6,
                'category_id' => 3,
                'name' => 'Boneka Rajut Kelinci Amigurumi',
                'description' => 'Boneka rajut tangan kelinci Amigurumi katun premium berbulu lembut, sangat pas untuk kado balita dan anak-anak.',
                'price' => 95000,
                'stock' => 15,
                'weight' => 200,
                'images' => ['/images/products/kelinci_amigurumi.jpg'],
                'tags' => ['Rajut', 'Boneka', 'Kelinci'],
                'style' => 'Cute',
                'target_demographic' => 'anak-anak',
                'rating_avg' => 4.8,
            ],
            [
                'shop_id' => 3,
                'category_id' => 3,
                'name' => 'Casing Handphone Rajut Stroberi',
                'description' => 'Pouch kantung pelindung handphone rajutan wool tebal bermotif strawberi 3D manis penahan goresan dan benturan.',
                'price' => 45000,
                'stock' => 25,
                'weight' => 100,
                'images' => ['/images/products/casing_stroberi.jpg'],
                'tags' => ['Casing HP', 'Rajut', 'Stroberi'],
                'style' => 'Cute',
                'target_demographic' => 'remaja',
                'rating_avg' => 4.5,
            ],
            [
                'shop_id' => 7,
                'category_id' => 3,
                'name' => 'Totebag Kanvas Lukis Hand-painted',
                'description' => 'Tas jinjing kanvas katun tebal dengan lukisan tangan cat akrilik bertema pemandangan alam abstrak, muat laptop kuliah 14 inch.',
                'price' => 75000,
                'stock' => 15,
                'weight' => 250,
                'images' => ['https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&auto=format&fit=crop'],
                'tags' => ['Totebag', 'Kanvas', 'Lukis Tangan'],
                'style' => 'Aesthetic',
                'target_demographic' => 'mahasiswa',
                'rating_avg' => 4.8,
            ],
            [
                'shop_id' => 7,
                'category_id' => 3,
                'name' => 'Cardigan Rajut Anak Motif Pelangi',
                'description' => 'Cardigan rajutan tangan berukuran pas untuk anak usia 3-5 tahun motif awan pelangi ceria benang wol hangat tidak gatal.',
                'price' => 185000,
                'stock' => 10,
                'weight' => 350,
                'images' => ['/images/products/cardigan_pelangi.png'],
                'tags' => ['Cardigan Rajut', 'Baju Anak', 'Pelangi'],
                'style' => 'Cute',
                'target_demographic' => 'anak-anak',
                'rating_avg' => 4.8,
            ],
            [
                'shop_id' => 2,
                'category_id' => 3,
                'name' => 'Sajadah Batik Tulis Indigo Alami',
                'description' => 'Sajadah empuk bermotif batik parang pewarna biru indigo alami dari tumbuhan nila, cocok untuk teman ibadah di kos.',
                'price' => 275000,
                'stock' => 8,
                'weight' => 450,
                'images' => ['/images/products/sajadah_indigo.jpg'],
                'tags' => ['Sajadah Batik', 'Indigo', 'Ibadah'],
                'style' => 'Etnik',
                'target_demographic' => 'mahasiswa',
                'rating_avg' => 4.9,
            ],

            // ── KATEGORI 4: Anyaman Serat Alam (category_id = 4, total 11 kriya) ──
            [
                'shop_id' => 3,
                'category_id' => 4,
                'name' => 'Keranjang Rotan Gantung Multifungsi',
                'description' => 'Keranjang anyaman rotan bulat dengan tali gantung sabut kelapa kuat, indah untuk tanaman rambat atau wadah buah.',
                'price' => 95000,
                'stock' => 25,
                'weight' => 400,
                'images' => ['/images/products/keranjang_rotan.jpg'],
                'tags' => ['Keranjang Rotan', 'Gantung', 'Anyaman'],
                'style' => 'Bohemian',
                'target_demographic' => 'remaja',
                'rating_avg' => 4.9,
            ],
            [
                'shop_id' => 3,
                'category_id' => 4,
                'name' => 'Tas Pandan Hias Renda Macrame',
                'description' => 'Tas jinjing anyaman daun pandan rajapolah dengan hiasan macrame rajutan serat katun boho, pas untuk liburan pantai.',
                'price' => 135000,
                'stock' => 15,
                'weight' => 300,
                'images' => ['/images/products/tas_pandan.jpg'],
                'tags' => ['Tas Pandan', 'Tas Pantai', 'Macrame'],
                'style' => 'Bohemian',
                'target_demographic' => 'remaja',
                'rating_avg' => 4.8,
            ],
            [
                'shop_id' => 3,
                'category_id' => 4,
                'name' => 'Tatak Gelas Macrame Boho (Set Isi 4)',
                'description' => 'Tatakan cangkir spiral rumbai dari pintalan serat katun alami, melindungi meja dari panas cangkir kopi estetik.',
                'price' => 42000,
                'stock' => 50,
                'weight' => 100,
                'images' => ['https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=600&auto=format&fit=crop'],
                'tags' => ['Tatakan Gelas', 'Macrame', 'Bohemian'],
                'style' => 'Bohemian',
                'target_demographic' => 'remaja',
                'rating_avg' => 4.7,
            ],
            [
                'shop_id' => 8,
                'category_id' => 4,
                'name' => 'Buku Jurnal Kulit Custom A5',
                'description' => 'Buku catatan jilid tangan dengan sampul kulit kerbau asli berkualitas rustic berserat, kertas daur ulang tebal ramah lingkungan.',
                'price' => 125000,
                'stock' => 20,
                'weight' => 450,
                'images' => ['https://images.unsplash.com/photo-1516414447565-b14be0adf13e?w=600&auto=format&fit=crop'],
                'tags' => ['Jurnal', 'Buku Catatan', 'Kulit'],
                'style' => 'Vintage',
                'target_demographic' => 'mahasiswa',
                'rating_avg' => 4.9,
            ],
            [
                'shop_id' => 3,
                'category_id' => 4,
                'name' => 'Binder Kuliah Kanvas Estetik (A5)',
                'description' => 'Binder 20 ring dari kain kanvas linen premium dengan penutup kancing magnet besi, membuat catatan kuliah Anda makin rapi.',
                'price' => 59000,
                'stock' => 45,
                'weight' => 400,
                'images' => ['/images/products/binder_kanvas.jpg'],
                'tags' => ['Binder', 'Linen', 'Kuliah'],
                'style' => 'Aesthetic',
                'target_demographic' => 'mahasiswa',
                'rating_avg' => 4.7,
            ],
            [
                'shop_id' => 8,
                'category_id' => 4,
                'name' => 'Dompet Kulit Kartu Slim Minimalis',
                'description' => 'Dompet kartu ramping kulit sapi jenis pull-up dengan 6 slot kartu and slot uang tunai di bagian tengah garansi keawetan.',
                'price' => 135000,
                'stock' => 25,
                'weight' => 150,
                'images' => ['/images/products/dompet_kartu.jpg'],
                'tags' => ['Dompet Kartu', 'Kulit Asli', 'Slim'],
                'style' => 'Minimalis',
                'target_demographic' => 'dewasa',
                'rating_avg' => 4.7,
            ],
            [
                'shop_id' => 8,
                'category_id' => 4,
                'name' => 'Tas Selempang Kulit Sapi Asli Ukir',
                'description' => 'Tas kulit premium berukiran parang batik Jawa, dijahit benang waxed manual sangat tangguh tahan air seumur hidup.',
                'price' => 780000,
                'stock' => 8,
                'weight' => 1200,
                'images' => ['/images/products/tas_kulit_sapi.jpg'],
                'tags' => ['Tas Kulit', 'Tas Selempang', 'Premium'],
                'style' => 'Etnik',
                'target_demographic' => 'dewasa',
                'rating_avg' => 5.0,
            ],
            [
                'shop_id' => 3,
                'category_id' => 4,
                'name' => 'Topi Anyaman Daun Pandan Lebar',
                'description' => 'Topi bundar pelindung terik matahari dari anyaman serat daun pandan pantai bertekstur, nyaman dipakai berlibur di alam terbuka.',
                'price' => 89000,
                'stock' => 15,
                'weight' => 250,
                'images' => ['/images/products/topi_pandan.jpg'],
                'tags' => ['Topi Anyaman', 'Topi Pantai', 'Serat Pandan'],
                'style' => 'Bohemian',
                'target_demographic' => 'remaja',
                'rating_avg' => 4.8,
            ],
            [
                'shop_id' => 8,
                'category_id' => 4,
                'name' => 'Nampan Anyaman Bambu Tradisional',
                'description' => 'Nampan saji atau tudung anyaman bambu rapat, dibersihkan dan dilapisi antijamur alami buatan pengrajin bambu Sleman.',
                'price' => 35000,
                'stock' => 30,
                'weight' => 200,
                'images' => ['https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=600&auto=format&fit=crop'],
                'tags' => ['Nampan Bambu', 'Anyaman Bambu', 'Alat Dapur'],
                'style' => 'Vintage',
                'target_demographic' => 'dewasa',
                'rating_avg' => 4.7,
            ],
            [
                'shop_id' => 3,
                'category_id' => 4,
                'name' => 'Keranjang Pakaian Rotan Besar',
                'description' => 'Keranjang tempat baju kotor silinder dari pilinan rotan alam kokoh dengan penutup atas, mempercantik lobi kamar kos mahasiswa.',
                'price' => 210000,
                'stock' => 12,
                'weight' => 2200,
                'images' => ['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&auto=format&fit=crop'],
                'tags' => ['Keranjang Rotan', 'Laundry Basket', 'Rotan Alam'],
                'style' => 'Aesthetic',
                'target_demographic' => 'mahasiswa',
                'rating_avg' => 4.8,
            ],
            [
                'shop_id' => 8,
                'category_id' => 4,
                'name' => 'Gantungan Kunci Kulit Ukir Inisial',
                'description' => 'Gantungan kunci kecil dari sisa potongan kulit sapi samak asli dengan ukiran ring kuningan anti karat bertema vintage retro.',
                'price' => 25000,
                'stock' => 100,
                'weight' => 50,
                'images' => ['/images/products/gantungan_kunci.jpg'],
                'tags' => ['Gantungan Kunci', 'Kulit Asli', 'Aksesori'],
                'style' => 'Vintage',
                'target_demographic' => 'remaja',
                'rating_avg' => 4.6,
            ],
            [
                'shop_id' => 3,
                'category_id' => 4,
                'name' => 'Hiasan Dinding Makrame Boho',
                'description' => 'Hiasan gantungan dinding gaya bohemian dari rajutan tali katun makrame alami, mempercantik estetika interior kafe atau ruang tamu.',
                'price' => 75000,
                'stock' => 15,
                'weight' => 500,
                'images' => ['https://images.unsplash.com/photo-1606744837616-56c9a5c6a6eb?w=600&auto=format&fit=crop'],
                'tags' => ['Makrame', 'Hiasan Dinding', 'Boho'],
                'style' => 'Bohemian',
                'target_demographic' => 'remaja',
                'rating_avg' => 4.8,
            ],
        ];

        foreach ($products as $prod) {
            Product::create($prod);
        }
    }
}